### PR TITLE
fix: autoscaler now requires 500MiB instead of 300MiB

### LINKED ISSUE #88: autoscaler is in crashloopbackoff after upgrading node-groups to latests ami linux
bug that I have encountered:

https://github.com/kubernetes/autoscaler/issues/4220

mitigation:

increase RAM limits from 300MiB to 500MiB

I will try to see if I can to change the defaults.

### PR DESCRIPTION
**Pull request by mercuriete**
* Fixes: #88
* Original issue: https://github.com/kubernetes/autoscaler/issues/4220

### CODE REVIEW

**Comment by mercuriete** [comment]
This is not tested yet.

I just opened the PR first and test later.

**Comment by mercuriete** [comment]
I already tested and deployed.

with this change we need to taint some resources because the terraform claims "there are no changes on the infrastructure"

but after destroying the module and applying the new module... it works for me.

you can review if this change is ok or not.

thanks.

**Review by Young-ook — APPROVED** [review]
LGTM

**Comment by Young-ook** [comment]
thank you!

**Pull request merged**
